parameters:
#    intra_correction.example.class: Intra\CorrectionBundle\Example

services:
#    intra_correction.example:
#        class: %intra_correction.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
