parameters:
#    intra_ticket.example.class: Intra\TicketBundle\Example

services:
#    intra_ticket.example:
#        class: %intra_ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
