parameters:
#    intra_admin.example.class: Intra\AdminBundle\Example

services:
#    intra_admin.example:
#        class: %intra_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
