<?php

namespace Intra\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
	public function getCommentairesBy($thread_id)
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->where("a.thread = '" . $thread_id . "'")
	                  ->orderBy('a.dateCreation', 'ASC')
	                  ->getQuery();

	 	return $query->getResult();
	}
}
