security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Intra\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:    ^/
            #fr3d_ldap:  ~
            provider: fos_userbundle
            form_login:
                always_use_default_target_path: true
                default_target_path: /profile
            logout:     true
            anonymous:  true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/correction, role: ROLE_USER }
        - { path: ^/module, role: ROLE_USER }
        - { path: ^/forum, role: ROLE_USER }
        - { path: ^/accueil, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/annuaire, role: ROLE_USER }
        - { path: ^/ticket, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
