<?php

namespace Intra\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaremecritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaremecritereRepository extends EntityRepository
{
}
