parameters:
#    intra_module.example.class: Intra\ModuleBundle\Example

services:
#    intra_module.example:
#        class: %intra_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
