parameters:
#    intra_user.example.class: Intra\UserBundle\Example

services:
#    intra_user.example:
#        class: %intra_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
