<?php

namespace Intra\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getAdmins()
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->where("a.roles LIKE '%ROLE_ADMIN%'")
	                  ->orderBy('a.username', 'DESC')
	                  ->getQuery();

	 	return $query->getResult();
	}
	
}
