<?php

namespace Intra\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends EntityRepository
{
	public function getReplys($ticketid)
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->where("a.ticket_id = '" . $ticketid . "'")
	                  ->orderBy('a.datetime', 'ASC')
	                  ->getQuery();

	 	return $query->getResult();
	}
}
