<?php

namespace Intra\TicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function getTickets($userid)
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->where("a.auteur = '" . $userid . "'")
	                  ->orderBy('a.datetime', 'DESC')
	                  ->getQuery();

	 	return $query->getResult();
	}

	public function getTicketsASC()
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->orderBy('a.datetime', 'DESC')
	                  ->getQuery();

	 	return $query->getResult();
	}

	public function getWaitingTickets()
	{
	    $query = $this->createQueryBuilder('a')
	    			  ->where("a.etat = 'En attente'")
	    			  ->orderBy('a.datetime', 'ASC')
	    			  ->orderBy('a.priorite', 'DESC')
	                  ->getQuery();

	 	return $query->getResult();
	}
}
