parameters:
#    intra_forum.example.class: Intra\ForumBundle\Example

services:
#    intra_forum.example:
#        class: %intra_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
